### ISSUE TITLE
Integration support tracker

### ISSUE THREAD

**Issue by pi0** [unjs/db0#50]
- [x] Dizzle (https://db0.unjs.io/integrations/drizzle)
- [ ] Prisma ([docs](https://www.prisma.io/))
- [ ] Typeorm ([docs](https://typeorm.io/))
- [ ] Kysely ([docs](https://github.com/kysely-org/kysely))
- [ ] Sequelize ([docs](https://sequelize.org/)
- [ ] MikroORM ([docs](https://mikro-orm.io/))

**Comment by MertcanYuzer** [comment]
Which orm is next? I wish it was Typeorm.

**Comment by adinvadim** [comment]
+ for next Typeorm

**Comment by vladkrasn** [comment]
Are Typeorm and MikroORM even possible? They rely on experimental decorators

**Comment by J3m5** [comment]
It would be nice to see [EdgeDB](https://www.edgedb.com/) supported

**Comment by Sandros94** [comment]
> It would be nice to see [EdgeDB](https://www.edgedb.com/) supported

@J3m5 for connectors, please refer to #32

**Comment by J3m5** [comment]
> > It would be nice to see [EdgeDB](https://www.edgedb.com/) supported
> 
> @J3m5 for connectors, please refer to #32

Well, I'm not talking only about the DB connector but especially about the tooling around it.
There is a Typescript client, a query builder, DB schemas, migrations etc

**Comment by Sandros94** [comment]
> Well, I'm not talking only about the DB connector but especially about the tooling around it. There is a Typescript client, a query builder, DB schemas, migrations etc

Absolutely!
Sorry for my barebone reply, but yes in general edgedb should probably have its own dedicated integration.
Although I still think that it requires its own connector first, if I'm not mistaken with the current structure of db0.

**Comment by pi0** [comment]
edgedb idea sounds lovely but if i'm not mistaken, it is a no-sql solution (while consider db0 is a SQL-multi connector)

I think it would be best to fork into a separate issue or discussion if we want to consider edgedb somehow.

**Comment by J3m5** [comment]
EdgeDB is actually based on PostgreSQL and uses its own DSL, which is parsed and then converted to SQL. 
Also, there is a Nuxt Module developed by @Tahul that might be useful for the implementation. 

Perhaps @Tahul could provide some insights with this integration.

**Comment by pi0** [comment]
~> https://github.com/unjs/db0/issues/94

**Comment by septatrix** [comment]
Another one for the list is Knex/Lucid

**Comment by CHIBX** [comment]
@pi0  Would a general adapter that could hook into these various ORMs be suitable?

**Comment by s3xysteak** [comment]
![image](https://github.com/user-attachments/assets/7c2f5ce6-aadf-4776-95ba-7df18e552f27)
Has anyone mentioned prisma yet? I really want it! 👀

**Comment by 642661520** [comment]
is there any progress?

**Comment by jacob-roling** [comment]
+1 for Kysely

**Comment by khangln-amv** [comment]
Any update on this?

drizzle integration for postgres and mysql has been merged [3-4 months ago](https://github.com/unjs/db0/pull/219), but there is no release since last year

**Comment by septatrix** [comment]
The linked PR only adds Prisma support, the others are still missing @pi0 (I assume this was GH Auto-Close feature and not on purpose)
